services:
  traefik:
    build:
      context: .
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    image: "traefik-local:v3.6"
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      # Les options prod (HTTPS + auth) sont dans traefik.prod.yml
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-certs:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
    networks:
      - web

networks:
  web:
    external: true

volumes:
  traefik-certs:
